# Generated by Django 4.2.25 on 2025-10-10 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.PositiveIntegerField(unique=True)),
                ('cname', models.CharField(max_length=100)),
                ('poster', models.ImageField(upload_to='poster/')),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='videos/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='flix.category')),
            ],
        ),
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.PositiveIntegerField(unique=True)),
                ('snum', models.PositiveBigIntegerField(unique=True)),
                ('simage', models.ImageField(upload_to='season_image/')),
                ('videos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='flix.videos')),
            ],
        ),
        migrations.CreateModel(
            name='Episodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.PositiveIntegerField(unique=True)),
                ('enum', models.PositiveIntegerField(unique=True)),
                ('videos', models.FileField(upload_to='episode_video/')),
                ('edesc', models.TextField()),
                ('seasons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='flix.seasons')),
            ],
        ),
    ]
