# Generated by Django 4.2.25 on 2025-10-10 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flix', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='episodes',
            unique_together={('enum', 'seasons')},
        ),
        migrations.AlterUniqueTogether(
            name='seasons',
            unique_together={('snum', 'videos')},
        ),
    ]
